# Generated by Django 4.2 on 2023-04-07 00:41

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="product.brand",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="product.product",
            ),
        ),
    ]
