# Generated by Django 4.2 on 2023-04-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_brand_parent_product_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brand",
            name="level",
        ),
        migrations.RemoveField(
            model_name="brand",
            name="lft",
        ),
        migrations.RemoveField(
            model_name="brand",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="brand",
            name="rght",
        ),
        migrations.RemoveField(
            model_name="brand",
            name="tree_id",
        ),
        migrations.RemoveField(
            model_name="product",
            name="level",
        ),
        migrations.RemoveField(
            model_name="product",
            name="lft",
        ),
        migrations.RemoveField(
            model_name="product",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="product",
            name="rght",
        ),
        migrations.RemoveField(
            model_name="product",
            name="tree_id",
        ),
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
